use latest collabwrapper.py
Fixes failure to start in Pippy-70, tested on Ubuntu 15.10, caused by
my mixing versions of collabwrapper sources.

Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 169, in <module>
    main()
  File "/usr/bin/sugar-activity", line 164, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/bin/sugar-activity", line 42, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/Pippy.activity/pippy_app.py", line 160, in __init__
    self.set_canvas(self.initialize_display())
  File "/usr/share/sugar/activities/Pippy.activity/pippy_app.py", line 387, in initialize_display
    self._source_tabs.add_tab()  # New instance, ergo empty tab
  File "/usr/share/sugar/activities/Pippy.activity/notebook.py", line 209, in add_tab
    buffer_text, editor_id, self._collab)
  File "/usr/share/sugar/activities/Pippy.activity/notebook.py", line 151, in __init__
    text_buffer, editor_id, collab)
  File "/usr/share/sugar/activities/Pippy.activity/texteditor.py", line 80, in __init__
    if not self._collab.props.leader:
AttributeError: 'gi._gobject.GProps' object has no attribute 'leader'