Save as library; only if writable
When the bundle is installed by the system the data directory is not
writable.  This causes;

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Pippy.activity/pippy_app.py", line 703, in _save_as_library
    with open(os.path.join(library_dir, file_name), 'w') as f:
IOError: [Errno 13] Permission denied: '/usr/share/sugar/activities/Pippy.activity/library/test.py'

Make the button insensitive if the data directory cannot be written to.