use collabwrapper in top directory
Fixes a regression introduced by ff5cb56 ...

Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 169, in <module>
    main()
  File "/usr/bin/sugar-activity", line 121, in main
    module = __import__(module_name)
  File "/usr/share/sugar/activities/Pippy.activity/pippy_app.py", line 78, in <module>
    from collabwrapper.collabwrapper import CollabWrapper
ImportError: No module named collabwrapper