Fix TypeError: Item 0: Must be number, not str
On pressing Go button;

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Pippy.activity/pippy_app.py", line 635, in _go_button_cb
    self._reset_vte()
  File "/usr/share/sugar/activities/Pippy.activity/pippy_app.py", line 608, in _reset_vte
    self._vte.feed('\x1B[H\x1B[J\x1B[0;39m')
TypeError: Item 0: Must be number, not str

Vte now requires bytes.