pippy_app: Verify source files names before exporting to distutils
Fix for
AttributeError: 'list' object has no attribute 'endswith'

Regression introduced 49b816b9a1467be033b26b898d31e1bdf924f511